doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Asset:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/Asset'
                prefix: 'App\Infra\Asset'
                alias: Doctrine
            Order:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/Order'
                prefix: 'App\Infra\Order'
                alias: Doctrine
            Source:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/Source'
                prefix: 'App\Infra\Source'
                alias: Doctrine
            Storage:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/Storage'
                prefix: 'App\Infra\Storage'
                alias: Doctrine
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/User'
                prefix: 'App\Infra\User'
                alias: Doctrine


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
