# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # http client
    http_client:
        scoped_clients:
            binance.rest.client:
                base_uri: https://api-gcp.binance.com/
                scope: https://api-gcp.binance.com
                headers:
                    Accept: 'application/json'
            bitget.rest.client:
                base_uri: https://api.bitget.com/
                scope: https://api.bitget.com/
                headers:
                    Accept: 'application/json'
            bybit.rest.client:
                base_uri: https://api.bybit.com/
                scope: https://api.bitget.com/
                headers:
                    Accept: 'application/json'
            coinbase.rest.client:
                base_uri: https://api.coinbase.com/
                scope: https://api.coinbase.com/
                headers:
                    Accept: 'application/json'
            kraken.rest.client:
                base_uri: https://api.kraken.com/
                scope: https://api.kraken.com/
                headers:
                    Accept: 'application/json'


    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
