<?php

declare(strict_types=1);

namespace App\Tests\Functional\Api\Client\RouterLoader;

use App\Infra\Source\ApiClient\ClientBuilder\Routes\Loaders\BybitRouteLoader;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Routing\RouteCollection;

class LoaderForProviderTest extends KernelTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRouterLoaderTest()
    {
        $routeLoader = new BybitRouteLoader();
        $routes = $routeLoader->load('bybit', 'yaml');
        $this->assertInstanceOf(RouteCollection::class, $routes);
    }
}