[package]
name = "PriceRequest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
ring = { version = "0.17.7", features = [] }
dotenv = "0.15.0"