parameters:
    bitget_api_key: '%env(string:BITGET_API_KEY)%'
    bitget_api_key_secret: '%env(string:BITGET_API_KEY_SECRET)%'
    bitget_api_key_passphrase: '%env(BITGET_API_KEY_PASSPHRASE)%'
    bybit_api_key: '%env(string:BYBIT_API_KEY)%'
    bybit_api_key_secret: '%env(string:BYBIT_API_KEY_SECRET)%'
    ext_rest_apis: ['bybit','bitget']

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Infra/Source/ApiClient/Client/Rest/'

    # External endpoints of providers
    App\Infra\Source\ApiClient\ClientBuilder\RestRouteLoader:
        arguments:
            - '%kernel.project_dir%'
            - '%ext_rest_apis%'

    App\Infra\Source\ApiClient\ClientBuilder\RestClientCredentials:
        arguments:
            -
                bitget:   [api_key: '%bitget_api_key%', api_key_secret: '%bitget_api_key_secret%', api_key_passphrase: '%bitget_api_key_passphrase%']
                bybit:    [api_key: '%bybit_api_key%', api_key_secret: '%bybit_api_key_secret%']
