parameters:
    bybit_rest_api_error: "https://bybit-exchange.github.io/docs/copy-trade/error"
    bitget_rest_api_error: "https://bitgetlimited.github.io/apidoc/en/spot/#restapi-error-code"
    binance_api_key: '%env(string:BINANCE_API_KEY)%'
    binance_api_key_secret: '%env(string:BINANCE_API_KEY_SECRET)%'
    bitget_api_key: '%env(string:BITGET_API_KEY)%'
    bitget_api_key_secret: '%env(string:BITGET_API_KEY_SECRET)%'
    bybit_api_key: '%env(string:BYBIT_API_KEY)%'
    bybit_api_key_secret: '%env(string:BYBIT_API_KEY_SECRET)%'
    coinbase_api_key: '%env(string:COINBASE_API_KEY)%'
    coinbase_api_key_secret: '%env(string:COINBASE_API_KEY_SECRET)%'
    kraken_spot_api_key: '%env(string:KRAKEN_SPOT_API_KEY)%'
    kraken_spot_api_key_secret: '%env(string:KRAKEN_SPOT_API_KEY_SECRET)%'
    kraken_futures_api_key: '%env(string:KRAKEN_FUTURES_API_KEY)%'
    kraken_futures_api_key_secret: '%env(string:KRAKEN_FUTURES_API_KEY_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Infra/Source/ApiClient/Client/Rest'

    _instanceof:
        App\Domain\Source\Api\Client\RouteLoader:
            public: true
            tags: ['rest.route_loader']


    App\Tests\Acceptance\Context\:
        resource: '../tests/Acceptance/Context/*'


    App\Infra\Source\ApiClient\ClientBuilder\RestRouteLoader:
        arguments:
            - '%kernel.project_dir%'
            - '%ext_rest_apis%'

    App\Infra\Source\ApiClient\ClientBuilder\RestClientCredentials:
        arguments:
            -
                binance:   [api_key: '%binance_api_key%', api_key_secret: '%binance_api_key_secret%']
                bitget:   [api_key: '%bitget_api_key%', api_key_secret: '%bitget_api_key_secret%']
                bybit:    [api_key: '%bybit_api_key%', api_key_secret: '%bybit_api_key_secret%']
                coinbase:    [api_key: '%coinbase_api_key%', api_key_secret: '%coinbase_api_key_secret%']
                kraken_spot:    [api_key: '%kraken_spot_api_key%', api_key_secret: '%kraken_spot_api_key_secret%']
                kraken_futures:    [api_key: '%kraken_futures_api_key%', api_key_secret: '%kraken_futures_api_key_secret%']
