parameters:
    bybit_rest_api_error: "https://bybit-exchange.github.io/docs/copy-trade/error"
    bitget_rest_api_error: "https://bitgetlimited.github.io/apidoc/en/spot/#restapi-error-code"
    bitget_api_key: '%env(string:BITGET_API_KEY)%'
    bitget_api_key_secret: '%env(string:BITGET_API_KEY_SECRET)%'
    bybit_api_key: '%env(string:BYBIT_API_KEY)%'
    bybit_api_key_secret: '%env(string:BYBIT_API_KEY_SECRET)%'
    ext_rest_apis: ['bybit','bitget']

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Infra/Source/ApiClient/Client/Rest'

    _instanceof:
        App\Domain\Source\Api\Client\RouteLoader:
            public: true
            tags: ['rest.route_loader']


    App\Tests\Acceptance\Context\:
        resource: '../tests/Acceptance/Context/*'


    App\Infra\Source\ApiClient\ClientBuilder\RestRouteLoader:
        arguments:
            - '%kernel.project_dir%'
            - '%ext_rest_apis%'

    App\Infra\Source\ApiClient\ClientBuilder\RestClientCredentials:
        arguments:
            -
                bitget:   [api_key: '%bitget_api_key%', api_key_secret: '%bitget_api_key_secret%', api_key_passphrase: '%bitget_api_key_passphrase%']
                bybit:    [api_key: '%bybit_api_key%', api_key_secret: '%bybit_api_key_secret%']
